# Basic C++ Coding Problems 
## I found these problems from the GitHub Repository https://github.com/Rustam-Z/cpp-programming?tab=readme-ov-file#problem-solving

- [x] C++ Program to print "Hello, World!".
- [x] C++ Program to print an integer entered by the user.
- [x] C++ Program to Add/Subtract/Multiply/Divide Two Integers.
- [x] C++ Program to Add/Subtract/Multiply/Divide Two Integers entered by the user.
- [x] C++ Program to Add/Subtract/Multiply/Divide two Floating Point Numbers.
- [ ] C++ Program to Compute Quotient and Remainder.
- [ ] C++ Program to Calculate the Area and Circumference of a Circle.
- [ ] C++ Program to Calculate the Area of a Scalene Triangle.
- [ ] C++ Program to Calculate the Area of an Equilateral Triangle.
- [ ] C++ Program to Calculate the Area of Right Angle Triangle.
- [ ] C++ Program to Calculate the Area and Perimeter of a Rectangle.
- [ ] C++ Program to Calculate the Area and Perimeter of a Square.
- [ ] C++ program that converts between Celsius and Fahrenheit temperatures based on user input. You can also add conversions for Kelvin.
- [ ] C++ Program to Find ASCII Value of a Character.
- [ ] C++ Program to Find the Size of int, float, double, and char.
- [ ] C++ Program to Check Whether a Number is Even or Odd.
- [ ] C++ Program to Check Whether a Number is Positive or Negative.
- [ ] C++ Program to Check Whether a Character is a Vowel or Consonant.
- [ ] C++ Program to find the Largest Number Among Three Numbers.
- [ ] C++ Program to find if the entered year is a leap year or not.
- [ ] C++ program that allows the user to perform basic arithmetic operations (addition, subtraction, multiplication, division) on two numbers. You can also add error handling for division by zero.
- [ ] BMI Calculator: Create a program that calculates a person's Body Mass Index (BMI) based on their weight and height input. Provide a classification of whether the person is underweight, normal weight, overweight, or obese. Use cin, cout. Formula: BMI = weight / (height * height)
